routes/web.php
Route::post('buscar_ci', 'MedicalRequestController@search_ci')
    ->name('buscar_ci.buscarci');
Route::post('buscar_solicitud', 'MedicalRequestController@search_medical_request')
    ->name('medical_request.search');
Route::post('buscar_empleado', 'MedicalRequestController@search_medical_request_employee')
    ->name('medical_request.search_more');
Route::get('imprimir/{code}', 'MedicalRequestController@print')
    ->name('medical_request.print');

Route::get('{id}/mostrar_archivos', 'MedicalRequestController@showFiles')
    ->name('mostrar_archivos.showFiles');

Route::get('getimage/{filename}', 'MedicalRequestController@displayImage')->name('image.displayImage');
Route::get('download_file/{filename}', 'MedicalRequestController@downloadFile')->name('image.downloadFile');

Route::get('importar_datos', 'MedicalRequestController@edit_import')
    ->name('importar_datos.edit');
Route::post('importar_datos', 'MedicalRequestController@update_import')
    ->name('importar_datos.update');
Route::group(['middleware' => ['auth']], function() {

    /**
     * RUTAS PARA LOS MEDICOS
     */
    Route::group(['middleware' => ['check_role:root,admin,medic,nurse']], function() {
        Route::resource('administracion_solicitudes','MedicalRequestAdministrationController');
        Route::prefix('administracion_solicitudes')->group(function () {
            Route::post('asignar_empleado', 'MedicalRequestAdministrationController@assignToEmploye')
                ->name('administracion_solicitudes.asignar_empleado.assignToEmploye');
            Route::post('asignar_medico', 'MedicalRequestAdministrationController@assignToMedic')
                ->name('administracion_solicitudes.asignar_medico.assignToMedic');
            Route::post('asignarme', 'MedicalRequestAdministrationController@assignToMe')
                ->name('administracion_solicitudes.asignarme.assignToMe');
            Route::post('no_encontrado', 'MedicalRequestAdministrationController@employeeNotFound')
                ->name('administracion_solicitudes.no_encontrado.employeeNotFound');
            Route::post('verificar_pre', 'MedicalRequestAdministrationController@verifyStatePreSol')
                ->name('administracion_solicitudes.verificar.verifyStatePreSol');
            Route::post('cerrar_pre', 'MedicalRequestAdministrationController@closeStatePreSol')
                ->name('administracion_solicitudes.cerrar_pre.closeStatePreSol');
            Route::post('cerrar_pre/automatic_close', 'MedicalRequestAdministrationController@closeChangeStateAuto')
                ->name('administracion_solicitudes.cerrar_pre.closeChangeStateAuto');
            Route::post('actualizar_tabla', 'MedicalRequestAdministrationController@updateRegisters')
                ->name('administracion_solicitudes.actualizar_tabla.updateRegisters');
            Route::post('importarExcel', 'MedicalRequestAdministrationController@importarExcel')
                ->name('administracion_solicitudes.importarExcel');
            Route::post('file', 'MedicalRequestAdministrationController@fileTmp')
                ->name('administracion_solicitudes.fileTmp');
            Route::post('file_remove', 'MedicalRequestAdministrationController@fileRemove')
                ->name('administracion_solicitudes.fileRemove');
        });

        Route::resource('consultas_medicas', 'MedicalConsultationsController')
            ->except(['show']);
        Route::prefix('consultas_medicas')->group(function () {
            Route::get('consultas_medicas/{medical_request_id}/get_attention_historial', 'MedicalConsultationsController@getAttentionHistorial')
                ->name('consultas_medicas.getAttentionHistorial');
            Route::get('realizadas', 'MedicalConsultationsController@indexMmedicalRequestClose')
                ->name('consultas_medicas.realizadas.indexMmedicalRequestClose');
            Route::get('agendar/citas', 'MedicalConsultationsController@indexMedicalRequestAgend')
                ->name('consultas_medicas.agendar');
            Route::get('modal/resumen', 'MedicalConsultationsController@getModalResumen')
                ->name('consultas_medicas.get_resumen');
            Route::get('consultas_medicas/imprimir/{attention_id}', 'MedicalConsultationsController@printAttention')
                ->name('consultas_medicas.imprimir');
            Route::get('get_signos_vitales/{medical_request_id}', 'MedicalConsultationsController@getSignosVitales')
                ->name('consultas_medicas.get_signos_vitales');

            Route::get('consultas_medicas/imprimir_receta/', 'MedicalConsultationsController@printPrescription')
                ->name('consultas_medicas.imprimir_receta');

        });
        Route::resource('antecedentes', 'AntecendentController');

    });

    Route::prefix('administracion_solicitudes')->group(function () {
        Route::get('{id}/mostrar_historial', 'MedicalRequestAdministrationController@showHistory')
            ->name('administracion_solicitudes.mostrar_historial.showHistory');
    });

    /**
     * RUTAS PARA LAS  ENFERMERAS Y MEDICOS
     */
    Route::group(['middleware' => ['check_role:root,admin,medic,nurse,resp_adm_seg,sup_admin,resp_seg,resp_adm_seg_resp_seg']], function() {

        Route::resource('citas', 'AppointmentController')
            ->except(['show']);
        Route::prefix('citas')->group(function () {
            Route::post('form', 'AppointmentController@getFormAppointment')
                ->name('citas.form.getFormAppointment');
            Route::post('{id}/edit_form', 'AppointmentController@getEditFormAppointment')
                ->name('citas.form.getEditFormAppointment');
            Route::post('get_appointments', 'AppointmentController@getAppointmentsFromUserDate')
                ->name('citas.get_appointments.getAppointmentsFromUserDate');
        });
    });

    Route::prefix('empleados')->group(function () {
        Route::get('busqueda_empresa/{enterprise_id}', 'EmployeeRRHHController@getEmployeeFromEnterprise')
            ->name('empleados.busqueda_empresa.getEmployeeFromEnterprise');
        Route::get('busqueda_carnet/{ci}/{ci_expedition}', 'EmployeeRRHHController@getEmployeeFromCI')
            ->name('empleados.busqueda_ci.getEmployeeFromCI');
    });

    /**
     * RUTAS PARA ENFERMERAS
     */
    Route::group(['middleware' => ['check_role:root,nurse,call_center,resp_adm_seg,sup_admin,resp_adm_seg_resp_seg']], function () {

        Route::resource('enfermera', 'NurseController')->except('show', 'destroy');
        Route::prefix('enfermera')->group(function () {
            Route::post('enfermera/buscar', 'NurseController@search_by_nurse')
                ->name('enfermera.search_by_nurse');
            Route::get('casos_doctor', 'NurseController@view_cases')
                ->name('enfermera.casos_doctor');
            Route::get('signos_vitales/{medical_request_id}', 'NurseController@getSignosVitales')
                ->name('enfermera.get_signos_vitales');
            Route::post('signos_vitales/store', 'NurseController@storeVitalSigns')
                ->name('enfermera.storeVitalSigns');
            Route::get('signos_vitales/edit/{medical_request_id}', 'NurseController@editSignosVitales')
                ->name('enfermera.editSignosVitales');
            Route::post('signos_vitales/update', 'NurseController@updateVitalSigns')
                ->name('enfermera.updateVitalSigns');
        });
    });

    /**
     * RUTAS DE ADMINISTRADORES
     */
    Route::group(['middleware' => ['check_role:root,admin']], function() {
        Route::resource('usuario', 'UserController');
        Route::post('medical_user', 'UserController@getpersonalmedical')
        ->name('usuario.getmedics');

        //Configuracion
        Route::prefix('configuracion')->group(function () {
            Route::resource('prioridades', 'MedicalRequestPrioritiesController');
            Route::resource('tipo', 'MedicalRequestTypesController');
            Route::resource('estado', 'MedicalRequestStatusController');
        });

        //Cvd States
        Route::resource('covid_estados', 'CovidStateController');

        //Treatment Stages
        Route::resource('tratamiento_etapas', 'TreatmentStageController');

        //Risk Types
        Route::resource('tipos_riesgo', 'RiskTypeController');

        //Laboratories
        Route::resource('laboratorios', 'LaboratoryController');

        //Weighting Levels
        Route::resource('niveles_ponderacion', 'WeightingLevelController');

        //Disease Criterias
        Route::resource('criterios_enfermedad', 'DiseaseCriteriaController');
        //Test Type
        Route::resource('tipos_prueba', 'TestTypeController');

        //Risk Stauses
        Route::resource('estados_riesgo', 'RiskStatusesController');

    });

    // Usuarios - Editar contraseña
    Route::get('usuario/editar.contrasena/{id}', 'UserController@editContrasena')
        ->name('usuario.edit_contrasena');
    Route::put('usuario/editar.contrasena/{id}', 'UserController@updateContrasena')
        ->name('usuario.update_contrasena');

    Route::get('/home', 'HomeController@index')->name('home');

    /**
     * RUTAS PARA LOS DE RECURSOS HUMANOS
     */
    Route::group(['middleware' => ['check_role:root,rrhh']], function() {
        Route::resource('consultas_medicas_pendientes', 'PendingRequestController')->except('show', 'destroy');
        Route::prefix('consultas_medicas_pendientes')->group(function () {
            Route::post('asignar_empleado', 'PendingRequestController@assignToEmployee')
                ->name('consultas_medicas_pendientes.asignar_empleado.assignToEmployee');
            Route::post('asignar', 'PendingRequestController@assign')
                ->name('consultas_medicas_pendientes.asignar.assign');
            Route::post('eliminar_solicitud', 'PendingRequestController@deleteRequest')

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable, SoftDeletes;

    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'users';

    /**
     * Indicates if the model should be timestamped.
     *
     * @var bool
     */
    public $timestamps = true;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'username','name', 'email', 'password', 'role_id','employee_id', 'rrhh_office_id'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     * @description = Obtiene el rol al que pertenece
     */
    public function role(){
        return $this->belongsTo(Role::class);
    }
    public function getUserameAttribute($value){
        return mb_strtoupper($value, 'UTF-8');
    }
    // SET Name
    public function setUsernameAttribute($value){
        $this->attributes['username'] = mb_strtoupper($value, 'UTF-8');
    }
    public function getFullNameAttribute(){
        if ($this->office!=null) {
            return $this->name.' ('.$this->office->direccion.')';
        } else {
            return $this->name.' (SIN ESPECIFICAR)';
        }
        
    }
    public function getFullNameRolAttribute(){
        if ($this->office!=null) {
            return $this->name.' ('.$this->role->name.' - '.$this->office->direccion.')';
        } else {
            return $this->name.' ('.$this->role->name.' - '.'SIN ESPECIFICAR'.')';
        }
        
    }

    public function employee(){
        return $this->belongsTo('App\EmployeeRRHH', 'employee_id');
    }
    public function office(){
        return $this->belongsTo('App\Office', 'rrhh_office_id');
    }
    public function medical_users(){
        return $this->belongsToMany('App\User', 'medical_users', 'nurse_id', 'doctor_id');
    }
    public function user_medical(){
        return $this->belongsToMany('App\User', 'medical_users', 'doctor_id', 'nurse_id');
    }
}

resources/views/medical_consultations/modals/content_modal.blade.php
<input type="hidden" name="medical_request_id" id="medical_request_id" value="{{ $medical_request->id }}">
<div class="modal-body">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-4">
                <label><i class="fa fa-barcode"></i><b> Codigo de Solicitud</b></label>
                <p id="p_modal_code">{{ $medical_request->code }}</p>
            </div>
            <div class="col-md-4">
                <label><i class="fa fa-user"></i><b> Nombre de empleado</b></label>
                <p id="p_modal_fullname">
                    @if($medical_request->employee!=null)
                        <span class="badge badge-success" data-toggle="tooltip" data-placement="top" title="Empleado asignado"><i class="fa fa-user-check"></i></span>
                        {{$medical_request->employee->full_name}}
                    @else
                        @if($medical_request->history_valid_status)
                            <span class="badge badge-info" data-toggle="tooltip" data-placement="top" title="Empleado validado"><i class="fa fa-user-check"></i></span>
                        @else
                            <span class="badge badge-danger" data-placement="top" title="Empleado sin asignar"><i class="fa fa-user-times"></i></span>
                        @endif
                        {{$medical_request->full_name}}
                    @endif
                </p>
            </div>
            <div class="col-md-4">
                <label><i class="fa fa-sort-numeric-desc"></i><b> CI</b></label>
                <p id="p_modal_full_ci">{{ $medical_request->full_ci }}</p>
            </div>
            <div class="col-md-4">
                <label><i class="fa fa-building"></i><b> Empresa</b></label>
                <p id="p_modal_enterprise">
                    @if($medical_request->employee!=null)
                        <span class="badge badge-success" data-toggle="tooltip" data-placement="top" title="Empleado asignado"><i class="fa fa-user-check"></i></span>
                        {{$medical_request->employee->enterprise->nombre}}
                    @else
                        @if($medical_request->history_valid_status)
                            <span class="badge badge-info" data-toggle="tooltip" data-placement="top" title="Empleado validado"><i class="fa fa-user-check"></i></span>
                        @else
                            <span class="badge badge-danger" data-placement="top" title="Empleado sin asignar"><i class="fa fa-user-times"></i></span>
                        @endif
                        {{$medical_request->enterprise}}
                    @endif
                </p>
            </div>
            <div class="col-md-4">
                <label><i class="fa fa-phone"></i><b> Telefono</b></label>
                <p id="p_modal_full_ci">
                    @if ($medical_request->whatsapp_flag)
                        <div class="badge badge-success">
                            <i class="fab fa-whatsapp"></i>
                        </div>
                    @endif
                    {{ $medical_request->phone_number }}
                </p>
            </div>
            <div class="col-md-4">
                <label><i class="fa fa-envelope"></i><b> Email</b></label>
                <p id="p_modal_email">{{ $medical_request->email }}</p>
            </div>
        </div>
        <div class="row">
            <div class="col-md-4">
                <label><i class="fa fa-edit"></i><b> Motivo de solicitud</b></label>
                <p id="p_modal_type">{{ $medical_request->medical_requests_type->name }}</p>
            </div>
            <div class="col-md-8">
                <label><i class="fa fa-comment"></i><b> Comentario u Observacion</b></label>
                <p id="p_modal_comment">{{ $medical_request->comment }}</p>
            </div>
        </div>
    </div>
    <hr>
    <div class="row">
        <div class="col-md-4 col-sm-12">
            <div class="form-row">
                <div class="form-group col-md-12 col-sm-12">
                    <label>{{ __('*Fecha de atención:') }}</label>
                    <div class="input-group">
                        <input type="text" class="form-control " id="fecha_consulta" name="fecha_consulta" value="{{ $fecha_actual->format('d/m/Y') }}">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class="far fa-calendar-alt"></i></span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-12" id="wrapper-status_id">
                    <label for="status_id" class="control-label col-12">{{ __('*Estado de la consulta') }}</label>
                    <div class="form-group">
                        <select id="medical_status_id" required value="{{ old('medical_status_id') }}" class="form-control select2 @error('medical_status_id') is-invalid @enderror" style="width: 100%;" name="medical_status_id">
                            <option></option>
                            @foreach($medical_request_status as $status)
                                <option value="{{$status->id}}">{{$status->name}}</option>
                            @endforeach
                        </select>
                    </div>
                    <span class="help-block">
                        <strong></strong>
                    </span>
                </div>
            </div>
            <div class="form-row">
                <label for="signos_vitales" class="control-label col-12">{{ __('Signos vitales') }}</label>
                <div class="col-sm-12 col-md-4">
                    <div class="input-group mb-3">
                        <div class="input-group-text">
                            <span class="">FC</span>
                        </div>
                        <input name="fc" id="fc" type="text" value="" class="form-control text-right" placeholder="">
                    </div>
                </div>
                <div class="col-sm-12 col-md-4">
                    <div class="input-group mb-3">
                        <div class="input-group-text">
                            <span class="">FR</span>
                        </div>
                        <input name="fr" id="fr" type="text" value="" class="form-control text-right" placeholder="">
                    </div>
                </div>
                <div class="col-sm-12 col-md-4">
                    <div class="input-group mb-3">
                        <div class="input-group-text">
                            <span class="">T°</span>
                        </div>
                        <input name="t" id="t" type="text" value="" class="form-control text-right" placeholder="">
                    </div>
                </div>
                <div class="col-sm-12 col-md-4">
                    <div class="input-group mb-3">
                        <div class="input-group-text">
                            <span class="">pa</span>
                        </div>
                        <input name="pa" id="pa" type="text" value="" class="form-control text-right" placeholder="">
                    </div>
                </div>
                <div class="col-sm-12 col-md-4">
                    <div class="input-group mb-3">
                        <div class="input-group-text">
                            <span class="">SaO2</span>
                        </div>
                        <input name="sao2" id="sao2" type="text" value="" class="form-control text-right" placeholder="">
                    </div>
                </div>
                <div class="col-sm-12 col-md-4">
                    <div class="input-group mb-3">
                        <div class="input-group-text">
                            <span class="">otros</span>
                        </div>
                        <input name="other" id="other" type="text" value="" class="form-control text-right" placeholder="">
                    </div>
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-12">
                    <label for="current_history" class="control-label col-12 my-0">{{ __('*Historia de la enfermedad actual') }}</label>
                    <div class="input-group mb-0">
                        <textarea name="current_history"  id="current_history" rows="3" value="" class="form-control placeholder="{{ __('Historia de la enfermedad actual') }}" required></textarea>
                    </div>
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-12">
                    <label for="physical_exam" class="control-label col-12 my-0">{{ __('*Examen fisico') }}</label>
                    <div class="input-group mb-0">
                        <textarea name="physical_exam"  id="physical_exam" rows="3" value="" class="form-control placeholder="{{ __('Examen fisico') }}" required></textarea>
                    </div>
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-12">
                    <label for="diagnostico" class="control-label col-12 my-0">{{ __('*Diagnostico') }}</label>
                    <div class="input-group mb-0">
                        <textarea name="diagnostico"  id="diagnostico" rows="3" value="" class="form-control" placeholder="{{ __('Diagnostico') }}" required></textarea>
                    </div>
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-12">
                    <label for="tratamiento" class="control-label col-12 my-0">{{ __('*Tratamiento') }}</label>
                    <div class="input-group mb-0">
                        <textarea name="tratamiento"  id="tratamiento" rows="3" value="" class="form-control" placeholder="{{ __('Tratamiento') }}" required></textarea>
                    </div>
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-12">
                    <label class="my-0">{{ __('*Fecha próxima atención:') }}</label>
                    <div class="input-group mb-0">
                        <input type="text" class="form-control " name="fecha_proxima_consulta" id="fecha_proxima_consulta" value="">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class="far fa-calendar-alt"></i></span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-8 col-sm-12" style="transform: traslate(0,0); height: 500px;overflow: auto;padding: 10px">
            @if ($cantidad == 0)
                <div class="alert alert-light" role="alert">
                    Sin registros
                </div>
            @else
                @if ($historial_total)
                    @include('medical_request.partials.time_line_employee', ['medical_request' => $medical_requests ])
                @else
                    @include('medical_request.partials.time_line', ['history' => $historial_requests ])
                @endif

            @endif
        </div>
    </div>
</div>
<!-- date-range-picker -->
<script src="{{ asset('adminlte/plugins/daterangepicker/daterangepicker.js') }}"></script>
<script>
    $(document).ready(function() {
        $('[data-mask]').inputmask();

        $('.select2').select2({
            theme: 'bootstrap4',
            placeholder: 'SELECCIONE UNA OPCIÓN'
        });

        $('#fecha_proxima_consulta').daterangepicker({
            "singleDatePicker": true,
            "showDropdowns": true,
            "autoApply": true,
            "linkedCalendars": false,
            "showCustomRangeLabel": false,
            "drops": "up",
            "minDate": "{{ $fecha_actual->format('d/m/Y') }}",
            autoUpdateInput: false,
            timePicker: true,
            timePickerIncrement: 15,
            locale: {
                format: 'DD/MM/YYYY hh:mm A'
            }
        }, function(start, end, label) {
            console.log('New date range selected: ' + start.format('DD/MM/YYYY hh:mm A') + ' to ' + end.format('DD/MM/YYYY hh:mm A') + ' (predefined range: ' + label + ')');
            this.element.val(start.format('DD/MM/YYYY hh:mm A'));
        });

        $('#fecha_consulta').daterangepicker({
            "singleDatePicker": true,
            "showDropdowns": true,
            "autoApply": false,
            "linkedCalendars": false,
            "showCustomRangeLabel": false,
            "drops": "auto",
            "maxDate": "{{ $fecha_actual->format('d/m/Y') }}",
            locale: {
                format: 'DD/MM/YYYY'
            }
        }, function(start, end, label) {
          console.log('New date range selected: ' + start.format('YYYY-MM-DD') + ' to ' + end.format('YYYY-MM-DD') + ' (predefined range: ' + label + ')');
        });
        $('#hora_siguiente_consulta').datetimepicker({
            format: 'LT'
        })
    });

    $('#medical_status_id').change(function (e) {
        var id_status = $(this).val();
        if (id_status != null && id_status == 4) {
            $('#fecha_proxima_consulta').attr('disabled', 'disabled');
            $('#tratamiento').removeAttr('required');
            $('#diagnostico').removeAttr('required');
        }
    });


</script>

resources/views/medical_consultations/modals/modal_antecedente.blade.php
<!-- Modal -->
<div class="modal fade" id="modal_antecedente" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered " role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="tituloModalAntecedente">{{ __('Registro de entecedente') }}</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            {!! Form::open(['id' => 'frm_antecedente']) !!}
            <input type="hidden" name="modal_antecedent_type_id" id="modal_antecedent_type_id" value="">
            <input type="hidden" name="modal_employee_id" id="modal_employee_id" value="{{ $medical_request->employee_id }}">
            <input type="hidden" name="modal_medical_request_id" id="modal_medical_request_id" value="{{ $medical_request->id }}">
            <input type="hidden" name="modal_antecedent_id" id="modal_antecedent_id" value="">
            <div id="form-row">
                <div class="form-group col-12">
                    <label for="" class="control-label col-12" id="tipo_antecedente"></label>
                </div>
                <div class="form-group col-12">
                    <label for="descripcion_antecedente" class="control-label col-12 my-0 text-uppercase">Descripción</label>
                    <div class="input-group mb-0">
                        <textarea name="descripcion_antecedente"  id="descripcion_antecedente" rows="3" value="" class="form-control" placeholder="Descripción" ></textarea>
                        <span class="invalid-feedback" role="alert">
                        </span>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">
                    <i class="fa fa-close"></i> Cerrar
                </button>
                <button type="button" class="btn btn-success" onclick="registrar_antecedente()"  id="btnModalRegistrar">
                    <i class="fa fa-save"></i> Registrar
                </button>
                <button type="button" class="btn btn-warning" onclick="editar_atecedente()" hidden id="btnModalModificar">
                    <i class="fa fa-edit" ></i> Modificar
                </button>
            </div>
            {!! Form::close() !!}
        </div>
    </div>
</div>

resources/views/medical_consultations/modals/modal_patient_assign.blade.php
<!-- Modal -->
<div class="modal fade" id="modal_patient_assign" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-xl" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">{{ __('asignación') }}</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            {!! Form::open(['id' => 'frm_asignacion']) !!}
            <input type="hidden" name="medical_request_id" id="medical_request_id" value="">
            <div id="frm_content">
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">
                    <i class="fa fa-close"></i> Cerrar
                </button>
                <button type="button" class="btn btn-success" onclick="registrar_asignacion()">
                    <i class="fa fa-save"></i> Asignar
                </button>
            </div>
            {!! Form::close() !!}
        </div>
    </div>
</div>